### ISSUE TITLE
Clarify stance on IP address literals

### ISSUE THREAD

**Issue by ekline** [capport-wg/7710bis#18]
"""
   The URI SHOULD NOT contain an IP address literal.

Why not, and how does it maintain interoperability to have this as SHOULD NOT, rather than MUST NOT?
"""

**Comment by ekline** [comment]
My recollection (possibly faulty), is that we could have made this a MUST NOT in large part because we want the URI to be identical across IPv4 and IPv6 -based options, but that going from SHOULD NOT to MUST NOT could be over-prescriptive.

Is my recollection correct, and would such a move be over-prescriptive?

**Comment by martinthomson** [comment]
That is right.  It is also somewhat more challenging to get a valid certificate for an IP address than a domain name.
